language: java

script: ./mvnw test jacoco:report coveralls:report

jdk:
- oraclejdk8

before_deploy:
  - mvn -DskipTests package

deploy:
  - provider: releases
    api_key:
      secure: DPRIV3pAe2m0HrKqPy4osL5I21MzKWUqASx1UB0cvYYGqTAPC5uRcR1xgz2VfkPkSRDYLIk+QMZg0UfrVpWxT/8E5Xivaf6WQL//ZNfNT8xgdcGM9nXSjCc7dsjnanpbsDXmt3u2v5Hd2z8amN2WeOn9110t1Y10nsjH68QToPF10TRBkaqGrNHszSyiJIx1qcCCMm3DGqqmqNpS4EC0UhpRjhLel2onF0ZgCKdMMn8uNh1SFiR9GqA/5qLH1Z9mirMowKH8haiFdzA3E26Z0LlyKYij/pkb1YJzXfdx3Gql0i0oWEYJjKYyGNL0NndEK/jf/yALY6VveW+aQTmGScWYN+TKdTU4gOBs1oAt5DI+b/6UA0QkBrPUi1RQ/K4LiRuG5nJnVaqytHQh60oxLZMIhWNOy03CVFVrA2/W5VxfBTip7TZtH09wKXiZx+dynvkh3idkPelWdzuH7qkh7MVS+iKEhbg6s+3V3leomt17quzsVwvJCdhZgxQ26vQSEYUJ4V1y1GOA0/e9xhbDQ9JAJI+RVwqrykYTHS51UB3GiacJJXnqXMce5o/vo4du1nUXHb7oafml7qObNGE2tp8yMji+5o8aqOMDk7S65RrYb4TOoYCy0ehA8Pvqp9a+BSmAKqSDFZ8TE/EdDtzN8uHYOoYyK7KDBr2aTLmPS+Y=
    file_glob: true
    file: 'target/frontpage-plugin-islieb-*.jar'
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-frontpage-plugin-islieb
  - provider: script
    script: echo "<settings><servers><server><id>snapshots.public.nexus.synyx.de</id><username>$NEXUS_USERNAME</username><password>$NEXUS_PASS</password></server></servers></settings>" > ~/settings.xml; mvn deploy --settings ~/settings.xml -DskipTests
    skip_cleanup: true
    on:
      branch: master
      repo: coffeenet/coffeenet-frontpage-plugin-islieb
  - provider: script
    script: echo "<settings><servers><server><id>releases.public.nexus.synyx.de</id><username>$NEXUS_USERNAME</username><password>$NEXUS_PASS</password></server></servers></settings>" > ~/settings.xml; mvn deploy --settings ~/settings.xml -DskipTests
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-frontpage-plugin-islieb

env:
  global:
  - secure: CIRcBsDsnTQUc3uJEFTEJrzU5Fb3X97+CQy3gZ9ANKOj64l+eZZ+PeNUYaEyLRwzFcAShRrANU18wyV6qvnT4DmdZA0aHQGpzy811PaN4qH1H43zmLVfnieIeylsKqYxAMbHcxpzulmdpGuP4MZnZI22Dd5b0TdeiMBNwgzl+x5OfDoqAPVE26/zOp+hEo0E3Ufc0xzcrdVWyuhO5ixjT687sD0o2piBGMyAiXOIBzruwRSB9UvRJ5nk/ILzn+awXVcGYuQx0f9QzSclhOjtOo0C/ISjGgeuCELZRdCRrnNhyaxLyeECnhYl0rOc75khu+vamV008Ek9RppL7QWEWZFk0/seboYVaEQA2/0BLjxDL8xJO9y7mCE4YR+1mdYCk6kb2FGN9LQ/HcDVre21C731CLsjNaIrxXNwotBbetiSE/4BAxxx4XyuvN0BB8ajdcc7OtciTWn5XdZ3X7xBVpUk/ZmbwMCfUU5o+7MMPwzbg34OaLcemOZMD1NIulrw+HAP4+xivkY0C1c2Rnu6d+gtDZleEBCfTqYHCU5JsscL43X8wxXRd0t1pxJGTeWDlvEeKPtuwgPJasdxDHmwBrSomLEAlAppnoO1sUicXZBIvA6F501ggtxQeHMMAnCDby3NzGTh0cbmnSZbN2Ey2iCoSKrkccTpe1pVZEWSzy4=
  - secure: fx/cVU7MxC0tap/bi2QMbxslqKG1OHe7pzVO4C9/WRBNp3ziXBOJj8+wo7dBfDymPv3VoSLv8hsmQ3RwCY6fg/GeuwCDkLbbj7ShgZ1rrPos2NSUR8T/Ike8hTX55YqFghDg8L4xSc4SSE1P5MH+VBNEirLwMpBBtCh2roavcT8CwUUGuL3qNkBEwXjbx3qTP2bo/CJAXbp1RRZD65GnQu0zQGI8WykMbRlV3iw29COh0G2KXjE6cyxL6YvPrylKIOEFZ7YZg2xdFwa0DLhcvQkK4mlPZ36ygY9KGOmtpIRBmhzqvJ3OsUIpyEedee/N66sM3/Y8dLG/jCG5OUP4sRxc6ocAHceb3Q6CgzsCcl4pOKJDtRjuUYbQ2U8Uz7rTsqrVGL+GXPbwJGnsGkGcGTUg+KvwPuzCRjtvmc103h/Z+k4WMfoYaBrlSOll+zcbORj4IGXs14weN4Pe6Vo3KGhv+M5R6UhzytKWZglsB3bNMuXAs+CijlsCqnu+e3IED+2ysMFLaVlzzyAY4quGHhGHcDUvdt3Q6nIDmc3rOm04N2vrFe6i2FrsHXA88+1j+zmWlARScrrG7TGsFGrDlUuvGy9dV2i1gUIdIksHUWKzdjrlaGBohoWccPVRPapQ+6T4+dIxZkuVj9bWGqT7MBUT113N/SyAkcoRYC8u1XY=

notifications:
  irc:
    channels:
      - "irc.synyx.de#CoffeeNet"
    on_success: change # default: always
    on_failure: always # default: always
    use_notice: true
    skip_join: true

cache:
  directories:
    - $HOME/.m2
